global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "service-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      # When `service-api` runs from IntelliJ on the host:
      - targets: ["host.docker.internal:8050"]

